created filters
baddazi/TodoList pull request #8
Opened 2021-03-25 19:32 UTC by baddazi

Created features: search and only this week

2021-03-25 20:25 UTC, pteasima requested changes

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +    func filterTodos(searched: String, isToggleOn: Bool){
the naming is garbage btw. I don't care that its a toggle, what does the toggle do? You had a somewhat good name for the variable, don't hesitate to use it for the parameter also. The fact that its inconsistent already tells you that its not good.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +    @State var searchedText:String = ""{
A good naming would be `query` or `queryText`, but this ok.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        let bindBool = Binding<Bool>(
I don't care that its a bool, what does it represent? Name it accordingly.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        let bindBool = Binding<Bool>(
btw theres a shortcut for creating bindings from `@State`, try `$isCheckedThisWeek`.

But its good that you found this `.init(get:set:)` initializer. You now know more about SwiftUI bindings that 90% of Swift programmers. Mostly people think its magic, don't understand that its just a getter and setter 😀

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        let bindBool = Binding<Bool>(
`self.` isn't needed btw. It would have been needed 6months ago :)

In general, try not to use whats not needed unless it significantly improves readability.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        let bindText = Binding<String>(
poor naming. If its "a binding to some text", it should be called `textBinding`, Im not saying thats good, but `bindText` makes no sense. `bindText` suggest that its a function which "binds some text" when called.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +                    Text("\(todo.name), " + "\(todo.createdAt))".prefix(20))
don't limit the String length, let SwiftUI do its thing. It will truncate as best it can, alternatively, you can allow the text to shrink etc.

No need to care about that now, my general point here is: Don't be smart by using magical constants like "20 of something", that clearly can't work well on all device types and sizes, the space available for the Text will differ.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        var tempTodos: [Todo] = todos
with functional style, you should rarely need local variables (most things can be `let` constants). Thats the beauty of FP, you don't need to manage mutable state (and I don't need to read it carefully, cause it will just be a chain of operators. There's nothing wrong with having `someArray.filter { ....}.filter {....}`, although we would probably merge the condition into one `filter` call

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +            tempTodos = tempTodos.filter{ todo in
Shit, I though you'd need map you actually didn't 🤦‍♂️😀. You'll practice `map` in due time. Good job.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        displayedTodos=tempTodos
so just to wrap up, this could have been

displayedTodod = todos.filter { todo in (searched.isEmpty || todo.name.uppercased().contains(searched.uppercased())) && (!isToggleOn || (Date().timeIntervalSinceReferenceDate - todo.createdAt.timeIntervalSinceReferenceDate) < 604800 )`

Im not saying you should do it like that, maybe its more readable with some helper variables, but you should need the complicated control-flow (if something then mutate something else do nothing, then if something......else do nothing), its all just one filter statement, albeit a complicated one.

2021-03-25 20:25 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +                return (Date().timeIntervalSinceReferenceDate - todo.createdAt.timeIntervalSinceReferenceDate) < 604800 } // 604800 is one week in sec.
creating `Date()` here is called a co-effect (you're reading the current date from the outside world). Its reasonable here to always use the latest current date at the time this is called, but I'd say at least use a single date (i.e. do `let currentDate = Date()` at the top of this method and use it from then on, don't create a new (slightly different) date for every element. This can result in very hard to debug bugs.


Btw, eventually, I would probably want to control the current date. Which can be as easy as `extension Date: EnvironmentKey { static var defaultValue: () -> Self = Date.init }` then use `@Environment(\.[key: \Date.self]) private var currentDate`

2021-03-26 14:56 UTC, pteasima requested changes
Needs to be this week, not last 7 days. Youll probably need a Calendar, I think theres one already in the Environment, so no need to define yours.

2021-03-26 14:56 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        self.todos.append(Todo(createdAt: Date(),name: "New Todo Name"))
should use the `currentDate` you added

2021-03-26 14:56 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        displayedTodos = todos.filter { todo in (searchedText.isEmpty || todo.name.uppercased().contains(searchedText.uppercased())) && (!isThisWeekChecked || (currentDate().timeIntervalSinceReferenc
`604800` could be `60*60*24*7`, much easier to understand.

Plus, I now realize its wrong anyway, I wanted todos from this week, not todos from the last 7 days.

2021-03-26 14:56 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        let isThisWeekCheckedBinding = Binding<Bool>(
if you get a chance, get rid of these and replace the, with the `$` version, its a well-known feature of SwiftUI, no reason not to use it.

2021-03-26 14:56 UTC, pteasima commented on TodoList/View/TodosListView.swift
> +        let isThisWeekCheckedBinding = Binding<Bool>(
you wont need the local variables either, it will be perfectly readable when you pass `$isThisWeekChecked` directly as the `isOn:` parameter

2021-03-26 21:37 UTC, baddazi commented
@pteasima ready for review

2021-03-26 22:46 UTC, pteasima commented
continue with #9 , we'll resolve this on a call sometime.

2022-03-29 11:26 UTC, closed without merging